openapi: 3.0.0
info:
  description: This file contains the OpenAPI specifications for The Furniture Bros API
  title: TheFurnitureBrosOpenAPI
  version: 1.0.0
servers:
  - url: http://thefurniturebros.com
    description: Production server
  - url: http://localhost:5000
    description: Local server
paths:
  /auth/register:
    post:
      summary: Register an Account
      description: This endpoint allows you to register a user. Once registered, it will return an API key.
      tags:
        - Auth
      requestBody:
        $ref: ./auth/register.yml
      responses:
        "200":
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: |
                      The API key used to authenticate the account.
                example:
                  token: "eyJhbGciOiJIUzI1NiIsInR5cBGlR1fkzXQKgxLshzVL2lcajQNXEUTH09N-csr98"
        "400":
          description: See message decription.
        "500":
          description: see message description.
      externalDocs:
        description: Learn more about JSON Web Token (JWT).
        url: https://auth0.com/docs/secure/tokens/json-web-tokens
