openapi: 3.0.0
info:
  description: This file contains the OpenAPI specifications for The Furniture Bros API
  title: TheFurnitureBrosOpenAPI
  version: 1.0.0
servers:
  - url: http://thefurniturebros.com
    description: Production server
  - url: http://localhost:5000
    description: Local server
paths:
  /auth/register:
    $ref: paths/auth/register.yml
